# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required
dist: xenial
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - gm130s@gmail.com
env:
  matrix:
    - CHECK_PYTHON3_COMPILE=true
    - ROS_DISTRO="kinetic" DOCKER_IMAGE=ubuntu:xenial
    - ROS_DISTRO="melodic" DOCKER_IMAGE=ubuntu:bionic
    - ROS_DISTRO="noetic"  DOCKER_IMAGE=ubuntu:focal
matrix:
  fast_finish: true
  allow_failures:
    - env: ROS_DISTRO="jade"
    - env: ROS_DISTRO="lunar"
before_script:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME from $CI_SOURCE_PATH"
script:
  - if [ "${CHECK_PYTHON3_COMPILE}" == "true" ]; then python3 -m compileall .; exit $?; fi
  - docker run --rm -i -v $CI_SOURCE_PATH:$CI_SOURCE_PATH -e "CI_SOURCE_PATH=$CI_SOURCE_PATH" -e "HOME=$HOME" -e "ROS_DISTRO=$ROS_DISTRO" -t $DOCKER_IMAGE sh -c "cd $CI_SOURCE_PATH; ./.travis.sh"
